# > PROJECT INFO
# NAME: CENTRAL DATA REPOSITORY CONSTRUCTION - LAND TENURE (IMAFLORA)
# LEAD: CLARISSA GANDOUR
#
# > THIS SCRIPT
# AIM: SAVE AN OBJECT WITH THE STATES NAMES AND UFS
# AUTHOR: DIEGO MENEZES
#
# > NOTES
# 1: -

#

states<-c("AC","AL","AM","AP","BA","CE","DF","ES","GO","MA","MG","MS","MT","PA",
          "PB","PE","PI","PR","RJ","RN","RO","RR","RS","SC","SE","SP","TO")
